name: build-renderer
on:
  push:
    branches: [ main ]
    paths: ['renderer/**']
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS creds (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::786673323159:role/GithubCdkDeployRole
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Discover ECR repo URI
        id: repo
        run: |
          URI=$(aws ecr describe-repositories --query "repositories[?contains(repositoryName,'RendererRepo')].repositoryUri | [0]" --output text)
          echo "uri=$URI" >> $GITHUB_OUTPUT
      - name: Build & Push
        run: |
          docker build -t renderer:latest ./renderer
          docker tag renderer:latest ${{ steps.repo.outputs.uri }}:latest
          docker push ${{ steps.repo.outputs.uri }}:latest
