name: Deploy uploadFn

on:
  push:
    paths:
      - 'lambdas/uploadFn/**'
      - '.github/workflows/uploadFn.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}
      LAMBDA_FUNCTION_NAME: uploadFn

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Zip & update function
        shell: bash
        working-directory: lambdas/uploadFn
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t .
          zip -r9 /tmp/uploadFn.zip .
          aws lambda update-function-code \
            --function-name "${LAMBDA_FUNCTION_NAME}" \
            --zip-file fileb:///tmp/uploadFn.zip >/dev/null
          # Ensure handler matches our file
          aws lambda update-function-configuration \
            --function-name "${LAMBDA_FUNCTION_NAME}" \
            --handler app.lambda_handler >/dev/null
