name: Deploy uploadFn

on:
  push:
    paths:
      - "lambdas/uploadFn/**"
      - ".github/workflows/uploadFn.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      LAMBDA_FUNCTION_NAME: ${{ secrets.LAMBDA_FUNCTION_NAME }}
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps into function folder
        working-directory: lambdas/uploadFn
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t .

      - name: Zip & deploy
        working-directory: lambdas/uploadFn
        run: |
          zip -r9 ../uploadFn.zip .
          aws lambda update-function-code --function-name "$LAMBDA_FUNCTION_NAME" --zip-file fileb://../uploadFn.zip
